trigger:
  branches:
    include:
      - main
  paths:
    include:
    - app
    exclude:
    - app/.azure-pipelines

pr:
  branches:
    include:
      - main
  paths:
    include:
    - app
    exclude:
    - app/.azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

variables:
  dotnetVersion: '7.0'
  buildConfiguration: 'Release'

steps:

- checkout: self
  fetchDepth: 0

- task: UseDotNet@2
  displayName: 'Install .NET $(dotnetVersion) SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion).x'

- script: |
    dotnet tool install GitVersion.Tool --tool-path $(Agent.ToolsDirectory)/dotnet/tools
    $(Agent.ToolsDirectory)/dotnet/tools/dotnet-gitversion /output json /output buildserver /updateprojectfiles
  displayName: SemVer GitVersion

- script: dotnet restore --nologo
  displayName: Restore
  workingDirectory: app

- script: dotnet build --nologo --no-restore -c $(buildConfiguration)
  displayName: Build
  workingDirectory: app

- script: dotnet publish --nologo --no-build src/WebApi -c $(buildConfiguration) --os linux --arch x64 -t:PublishContainer -p:PublishProfile=DefaultContainer
  displayName: Create OCI Image
  workingDirectory: app

- task: DownloadSecureFile@1
  inputs:
    secureFile: dockerhub_pat.key
    retryCount: 2

- script: |
    cat dockerhub_pat.key | docker login --username lsquared --password-stdin
    docker push lsquared/apps_weather:$(GitVersion.SemVer)
    docker push lsquared/apps_weather:latest
  displayName: Push OCI Image to DockerHub
  condition: ne(variables['Build.Reason'], 'PullRequest')
