repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.1
  hooks:
  - id: commitizen
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: fix-byte-order-marker
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: detect-private-key
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.77.0
  hooks:
  - id: terraform_fmt
  #- id: terraform_validate
  #- id: terraform_docs
  #- id: terraform_tfsec
